### ISSUE TITLE
Research current or similar software solutions

### ISSUE THREAD

**Issue by cvraut** [cvraut/MGMFSD#1]
According to Brian the BROAD is kinda the organization that is running this stuff.

They might already have a tool out there that does this, look for it

**Comment by cvraut** [comment]
don't spend >2 hours

**Comment by cvraut** [comment]
https://www.synthego.com/guide/how-to-use-crispr/sgrna

So that article has a section on the various different guide designer software currently out there.

I don't know how many are free, it seems that they prioritize making sure the cuts don't botch up other parts of the cell... worth looking into whether they offer chance of frameshift

**Comment by oliveriantonino** [comment]
I checked them all except for _Benchling CRISPR Guide RNA Design tool_ which is not free. Only _CHOP CHOP_ mentions information related to frameshift mutations among the provided results. I showed it to Prabhu to figure out if that could help us. We looked at the results together and he said that is likely not helpful. He said what we are trying to see it is _unique_ (quote) and he would be surprised if some website came out with that. But he said Chop Chop seems better to design guides compared to Synthego, so maybe it wasn't all for nothing from their end

**Comment by cvraut** [comment]
@oliveriantonino sorry for the delay. Thank you for looking into this.
It might be worth including a brief writeup/presentation slide abt what was done before & what the other products do.

I will close this issue now & proceed with the construction of the rest of the project.
